
before_install:
  - lsb_release -a
  - sudo apt-add-repository --yes ppa:ubuntugis/ubuntugis-unstable
  #- sudo apt-add-repository --remove --yes ppa:cartodb/gis
  #- sudo apt-add-repository --remove --yes ppa:cartodb/postgresql-9.3
  - sudo apt-get update 
  #- sudo apt-cache search gdal
  #- sudo apt-cache search libspatialite5
  #- sudo apt-cache show libgdal-dev
  #- sudo apt-cache show libgdal1h
  #- sudo apt-cache show libgdal1
  #- sudo apt-get remove --purge libgdal1h
  #- sudo apt-get remove --purge libgdal1
  #- sudo apt-get remove --purge libgdal1h
  #- sudo apt-get install -q libgdal-dev 
  #- sudo apt-cache search postgis
  #- sudo apt-cache show postgresql-9.3-postgis-2.1
  #- sudo apt-cache show postgresql-9.1-postgis-2.1
  #- sudo apt-cache show postgresql-9.0-postgis-2.1
  #- sudo apt-get install -q postgresql-9.1-postgis-2.1
  #- sudo apt-get remove --purge libgdal1h
  #- sudo apt-get remove --purge gdal-bin
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal1-dev
  - sudo apt-get install python-gdal
  - sudo apt-cache show postgresql-9.1-postgis-2.0
  - sudo apt-get remove --purge postgresql-9.3-postgis-scripts
  - sudo apt-get remove --purge postgresql-9.2-postgis-scripts
  - sudo apt-get remove --purge postgresql-9.1-postgis-scripts
  - sudo apt-get install --reinstall -q postgresql-9.1-postgis-2.0
  - sudo apt-get install --reinstall -q postgresql-9.1-postgis-2.0-scripts
  - find /usr/share/postgresql/9.1/contrib/postgis*
  - dpkg -L postgresql-9.1-postgis-2.0-scripts
  - dpkg -l | grep postgis
  - sudo apt-get install postgresql-plpython-9.1
  - sudo apt-get install -q unp zip ruby1.9.3 ruby1.9.1-dev python-pip ruby-rspec libicu-dev 
  #- sudo pip install -I gdal=1.10.0 
  #- sudo pip install -I gdal=1.10.0 || cat /home/travis/.pip/pip.log && false
  - sudo apt-get install gdal-bin
  - gdal-config --version
  - createdb template_postgis
  - psql -c "SELECT VERSION();" template_postgis
  - psql -f ./usr/share/postgresql/9.1/contrib/postgis-2.0/postgis.sql template_postgis

install:
  - ruby --version
  - sudo gem install bundler
  # http://stackoverflow.com/questions/10916784/error-installing-debugger-linecache-in-ruby-1-9-3
  - gem install debugger-linecache -v '1.1.2' -- --with-ruby-include=$rvm_path/src/ruby-1.9.3-p484/
  - bundle install
  - cp config/app_config.yml.sample config/app_config.yml
  - cp config/database.yml.sample config/database.yml
  - sudo pip install -r python_requirements.txt
  # For python-gdal, see http://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip/64244#64244
  - cat python_requirements.txt | grep -v gdal | pip install -r /dev/stdin

script:
  - make check

env:

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
