language: ruby

before_install:
  - sudo add-apt-repository --remove --yes ppa:cartodb/gis
  - sudo apt-get update -q
  - sudo apt-get install -q postgis unp zip postgresql-plpython-9.1 ruby1.9.3 python-pip python-gdal ruby-rspec libicu-dev libgdal1 gdal-bin libgdal-dev 
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis

install:
  - sudo gem install bundler
  - sudo bundle install
  - cp config/app_config.yml.sample config/app_config.yml
  - cp config/database.yml.sample config/database.yml
  - sudo pip install -r python_requirements.txt

script:
  - make check

env:
  # For python-gdal, see http://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip/64244#64244
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal 

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
