
before_install:
  - lsb_release -a
  #- sudo apt-add-repository --remove --yes ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-add-repository --yes ppa:cartodb/gis
  - sudo apt-add-repository --yes ppa:cartodb/postgresql-9.3
  - sudo apt-get update 
  - sudo apt-cache search gdal
  - sudo apt-cache search libspatialite5
  - sudo apt-cache show libgdal-dev
  - sudo apt-cache show libgdal1h
  - sudo apt-cache show libgdal1
  #- sudo apt-get remove --purge libgdal1h
  #- sudo apt-get remove --purge libgdal1
  #- sudo apt-get remove --purge libgdal1h
  #- sudo apt-get install -q libgdal-dev 
  #- sudo apt-cache search postgis
  - sudo apt-cache show postgresql-9.3-postgis-2.1
  #- sudo apt-cache show postgresql-9.1-postgis-2.1
  #- sudo apt-cache show postgresql-9.0-postgis-2.1
  #- sudo apt-get install -q postgresql-9.1-postgis-2.1
  - sudo apt-get install -q postgresql-9.3-postgis-2.1
  - sudo apt-get install postgresql-plpython-9.3
  - sudo apt-get install -q unp zip ruby1.9.3 python-pip ruby-rspec libicu-dev 
  - sudo apt-cache show gdal-bin
  - sudo apt-get install gdal-bin
  - gdal-config --version
  # For python-gdal, see http://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip/64244#64244
  # CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal 
  #- sudo pip install -I gdal=1.10.0 || cat /home/travis/.pip/pip.log && false
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis

install:
  - sudo gem install bundler
  - bundle install
  - cp config/app_config.yml.sample config/app_config.yml
  - cp config/database.yml.sample config/database.yml
  - sudo pip install -r python_requirements.txt
  - cat python_requirements.txt | sed 's/^gdal==.*/gdal>=1.9.0/' | pip install -r /dev/stdin

script:
  - make check

env:

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
