
before_install:
  - lsb_release -a
  - sudo apt-add-repository --remove --yes ppa:cartodb/gis
  - sudo apt-add-repository --yes ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -q
  - sudo apt-get install -q libgdal1 libgdal-dev postgis unp zip postgresql-plpython-9.1 ruby1.9.3 python-pip ruby-rspec libicu-dev 
  - gdal-config --version
  # For python-gdal, see http://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip/64244#64244
  # CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal 
  - sudo pip install -I gdal=1.10.0 || cat /home/travis/.pip/pip.log && false
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis

install:
  - sudo gem install bundler
  - bundle install
  - cp config/app_config.yml.sample config/app_config.yml
  - cp config/database.yml.sample config/database.yml
  - sudo pip install -r python_requirements.txt

script:
  - make check

env:

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
